Fixed the Server Down Issue
FNNDSC/ChRIS_ui pull request #247
Opened 2021-04-19 19:13 UTC by mocktarissa

I added a feedback to the User when the server is down instead of just sayInvalid Credentials'

2021-04-20 20:23 UTC, jennydaman requested changes
Delete `yarn.lock

2021-04-20 20:23 UTC, jennydaman commented on src/pages/LogIn/components/LoginForm.tsx
> +        errorMessage:(()=>error.message==='Bad server response!'?'Invalid Credentials':error.message)(),
`error.message` is not a stable API. Use other fields of `error` instead, perhaps `error.response`
https://github.com/FNNDSC/fnndsc/blob/f9fda903aa791c484123e9b9ec186a7fd0c3ec3a/js/chrisAPI/src/request.js#L179

2021-04-20 20:23 UTC, jennydaman commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Delete `yarn.lock`. This project is managed by `npm`, not `yarn`

2021-04-21 12:07 UTC, jennydaman commented on src/pages/LogIn/components/LoginForm.tsx
> +        errorMessage:(()=>error.response?'Invalid Credentials':'There was a problem connecting to the server!')(),
I suppose [`@fnndsc/chrisapi`](https://github.com/FNNDSC/fnndsc/tree/master/js/chrisAPI) itself does not have the best exception objects. Maybe a PR there first would help?

But still you could be doing a `error.response.status === 200` or some other strong assertion.

```json
{
  "columnNumber": 12,​
  "fileName": "http://localhost:3000/static/js/vendors~main.chunk.js",
​  "lineNumber": 14154,
​  "message": "Bad server response!",
  "name": "o",​
  "request": XMLHttpRequest { readyState: 4, timeout: 30000, withCredentials: false, ... },
​  "response": { 
    "data": "Bad server response!",
    "status": 404,
    "statusText": "Not Found",
    ...
  },
  "stack": "a super long string..."
}
```

2021-04-21 13:07 UTC, mocktarissa commented
That was the first change I tried to make but when the server is down the response object returns null
This is what @fnndsc/chrisapi returns. 
```
{
    "error": {
        "name": "o",
        "request": {},
        "response": null
    }
}
```
The response object is set to null that's why I wrote it that way.

2021-04-25 14:04 UTC, mocktarissa commented
@PintoGideon Can you Take a look to check if everything is in order?

2021-04-25 14:10 UTC, jennydaman commented on src/pages/SignUp/components/SignupForm.tsx
> +        console.log({error});
Consider [`console.error`](https://developer.mozilla.org/en-US/docs/Web/API/Console/error)

2021-04-25 14:26 UTC, jennydaman commented on src/pages/LogIn/components/LoginForm.tsx
> +      console.log({error});
Seeing https://github.com/FNNDSC/ChRIS_ui/pull/247/commits/961ab97d533959d4cfb0a5e68286229cbdfedc0d, is your choice to not use `console.log`? If so, then delete this one too.

2021-04-25 20:19 UTC, jennydaman approved these changes

2021-04-25 20:19 UTC, merged